### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by jalandis** [lustre-labs/lustre#106]
While reviewing the documentation I noticed a few links are broken.

```
//// The `Effect` type here encompasses things like HTTP requests and other kinds
//// of communication with the "outside world". You can read more about effects
//// and their purpose in the [`effect`](./effect) module.
```

https://github.com/lustre-labs/lustre/blob/main/src/lustre.gleam#L81

It seems like the `.html` extension is required or else your dropped on a 404 page.  There may be a few other cases of this in the Gleam and Lustre projects also.

Happy to create a PR with the missing extension added if that is helpful.

**Comment by hayleigh-dot-dev** [comment]
Hey thanks for letting me know! I've gone through and fixed all the ones I could find, if you run into any more please let me know (or fix them ❤️) it's really frustrating hex doesn't handle this but perhaps I'm just lazy ^.^

thanks again!
