### ISSUE TITLE
State resets after saving changes

### ISSUE THREAD

**Issue by xpressivecode** [lustre-labs/lustre#129]
OS: osx 13.4.1 
gleam version: 1.1.0
lustre version: 4.2.2

https://github.com/xpressivecode/lustre-state-hydration

This above uses the example from the lustre repo. If you click the increment button a few times and add a new paragraph tag, the counter  resets to 0 after saving your changes.

**Comment by hayleigh-dot-dev** [comment]
Hey there, I think you're talking about lustre_dev_tools' live reloading feature. This is totally expected, it's not a bug.

Implementing hot module replacement (HMR) is a very difficult problem, I'd welcome someone taking a look at it though ^..^
