### ISSUE TITLE
https://hexdocs.pm/docs leads to Page Not Found

### ISSUE THREAD

**Issue by martimatix** [lustre-labs/lustre#13]
In the readme file, there's a link to https://hexdocs.pm/docs which leads to a Page Not Found page.

**Comment by hayleigh-dot-dev** [comment]
Hey there, thanks for the issue! I couldn't find the exact link you're talking about, but I went through and updated all the docs links anyway so hopefully that's sorted now :) Let me know if anything is still missing!
