### ISSUE TITLE
Server component click event errors

### ISSUE THREAD

**Issue by HHlambda** [lustre-labs/lustre#141]
When attaching click events to rows of a table the events produce "[4,null,{"data":{}}]" messages. I have attached an altered"99-server-components" counter file to reproduce the error.

[counter.txt](https://github.com/user-attachments/files/15744469/counter.txt)

**Comment by hayleigh-dot-dev** [comment]
Fixed in v4.2.5!

**Comment by HHlambda** [comment]
Working great. Thank you :)
