### ISSUE TITLE
Rebar3 Not Found When Running `gleam run -m lustre/dev start` from VS Code's PowerShell

### ISSUE THREAD

**Issue by Francisco-Montanez** [lustre-labs/lustre#147]
# Description

When attempting to run the command gleam run -m lustre/dev start from PowerShell integrated in Visual Studio Code, the system fails to find rebar3.cmd despite it being installed and accessible from the standalone PowerShell.

# Environment

Operating System: Windows
Visual Studio Code Version: latest version
Rebar3 Version: 3.23.0

# Steps to Reproduce

1. Open PowerShell through VS Code.
2. Navigate to the project directory
3. Run the command:
>gleam run -m lustre/dev start

Observe the error indicating that rebar3.cmd was not found.

# Expected Behavior
The command should execute without errors, recognizing the installed rebar3.cmd.

# Actual Behavior

The system reports:

>error: Program not found. The program `rebar3.cmd` was not found. Is it installed?

# Additional Information

The rebar3.exe is correctly installed and works outside of VS Code's PowerShell.

The PATH environment variable includes the path to rebar3.exe.

Rebar3 was installed via Chocolatey.

# Questions

Is rebar.exe different than rebar3.cmd?
Does it need to be run in an administrator shell? I tried both but neither worked.

# Exact console commands:

>PS C:\Users\F\Desktop\webapp> gleam run -m lustre/dev start
  Compiling argv
  Compiling gleam_stdlib
  Compiling ranger
  Compiling birl
  Compiling exception
  Compiling filepath
  Compiling fs
error: Program not found

>The program `rebar3.cmd` was not found. Is it installed?

>PS C:\Users\F\Desktop\webapp> rebar3
Rebar3 is a tool for working with Erlang projects.

>Usage: rebar3 [-h] [-v] [<task>]

 > -h, --help     Print this help.
 > -v, --version  Show version information.
>  <task>         Task to run.

>  Set the environment variable DEBUG=1 for detailed output.

**Comment by hayleigh-dot-dev** [comment]
Hey there! This isn't really a Lustre issue and I'm not a Windows user so I'm not sure how much help I can be ^.^ I suggest you drop a comment in the discussion on the [choco package](https://community.chocolatey.org/packages/rebar3#discussion) and see if anyone has any ideas.
