### ISSUE TITLE
Component example

### ISSUE THREAD

**Issue by hfjallemark** [lustre-labs/lustre#148]
Lustre looks really interesting! Do you have an example of how to use a component with its own state handling? I think I understand the `component` function and how you pass in data but how do you dispatch events back to the caller?

**Comment by hayleigh-dot-dev** [comment]
You can use `event.emit` to emit dom events from your update function.

So you'd have an `Effect` like:
```gleam
event.emit("my-custom-event", json.object([
  #("wibble", json.int(1)),
  #("wobble", json.string("hello"))
]))
```

The parent element could listen to it like any other event
```gleam
element("your-component", [
  event.on("my-custom-event", fn(event) {
    use #(wibble, wobble) <- result.try(
      // your custom event data is under the "detail" field
      // of the event object
      dynamic.field("detail", dynamic.tuple2(
        dynamic.int,
        dynamic.string
      )) 
    )
  })
], [
  ...
])
```

**Comment by hfjallemark** [comment]
Awesome! Thanks.
