### ISSUE TITLE
Example 03-controlled-inputs seems to be broken

### ISSUE THREAD

**Issue by fattenap** [lustre-labs/lustre#153]
Hi,

I ran the 03-controlled-inputs example and it does not seem to be working as expected. I tested in Chrome, Firefox and Safari.

I'm on gleam v. 1.2.1

![Jun-28-2024 23-19-38](https://github.com/lustre-labs/lustre/assets/4471171/2a310f5e-c1f4-4092-9419-e87f656ab7fd)

**Comment by dvic** [comment]
@fattenap so it's working, or?

**Comment by fattenap** [comment]
This is the current expected behaviour.

[discord chat](https://discord.com/channels/768594524158427167/1257180354939326475/1257200211965775873)
