### ISSUE TITLE
✨ Implement a `fragment` to contain multiple elements at once

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [lustre-labs/lustre#16]
In other frameworks it's often quite handy to be able to return multiple elements without wrapping them in some single container. Lustre should support this too! We should define a new
variant of the `Element` type...

```diff
  pub opaque type Element(msg) {
    ...
+   Fragment(List(Element(msg))
    ...
  }
```

... as well as exposing a new constructor for it.

```gleam
pub fn fragment(children: List(Element(msg)) -> Element(msg) {
  Fragment(children)
}
```

Then the render methods `to_string` and `to_string_builder` as well as the runtime need to be updated to support this new element type.

**Comment by giacomocavalieri** [comment]
If this is still up for grabs, I'd love to try implementing it!

**Comment by JScearcy** [comment]
Cool package! Curious if help is still wanted on this? I think there was some drift in the current implementation vs what's there today but I think I have enough understanding to put this together

**Comment by hayleigh-dot-dev** [comment]
If you think you could work it out I'd be very grateful! It has so-far eluded me, I'd appreciate someone that knows what they're doing chiming in 😅

**Comment by JScearcy** [comment]
Awesome, thanks! I'll post an initial approach this afternoon for consideration

**Comment by JScearcy** [comment]
I posted an initial draft PR, if anyone has feedback or suggestions I'm happy to update, after an initial round I can work on a more complete integration. Initially I just focused on the client runtime

**Comment by hayleigh-dot-dev** [comment]
If you're on discord feel free to drop me a DM @hayleigh.dev ^.^
