### ISSUE TITLE
lustre/element fragment doesn't update child elements properly

### ISSUE THREAD

**Issue by yoonthegoon** [lustre-labs/lustre#160]
## Problem

When a fragment has child elements that are removed (like from a model being updated), those elements are not totally removed.

This is different from the behavior of a div.

## Visual

Below is my initial state.

![image](https://github.com/user-attachments/assets/d1d7f68c-0938-4b66-b62a-2affe5fa504b)

Containing everything will either be a div or fragment.
In both scenarios, I remove the top transaction form.

### div

![image](https://github.com/user-attachments/assets/332aa606-0ea2-4b50-98cf-b0cf93c5d84a)

### fragment

![image](https://github.com/user-attachments/assets/6f26f55a-318e-406c-96f5-d12249352bf3)

As you can see, removing the top transaction form in a fragment leaves the total count of forms the same, simply duplicating the last form and associating those forms with the same transaction in my model.

**Comment by JScearcy** [comment]
I was able to reproduce, working on a fix now!

**Comment by hayleigh-dot-dev** [comment]
I _believe_ this is fixed now, please re-open if you run into anything again!
