### ISSUE TITLE
Question about the return value of main function in the example

### ISSUE THREAD

**Issue by soomtong** [lustre-labs/lustre#163]
Just a question, innocently looking at the example code 🙏🏼 
Is there a reason why the main function returns Nil?

If this question has no value, you can just close the issue.

**Comment by hayleigh-dot-dev** [comment]
No real reason! In Gleam your `main` can return anything, but I like to have it return `Nil` if I'm not expecting to use the return type from some JavaScript FFI: it's just habit / personal preference :)
