### ISSUE TITLE
VDOM reuses <textarea> without updating its value

### ISSUE THREAD

**Issue by pocka** [lustre-labs/lustre#169]
## Overview

- Lustre v4.3.2
- Gleam v1.4.0

Current VDOM implementation does not update `<textarea>`'s value when reusing elements.
This is noticeable when inserting/prepending `<textarea>` to a list that has another `<textarea>`.

https://github.com/user-attachments/assets/bf6f42a4-2180-4d8d-988d-fb6b1c2b1bed

<details>
<summary>Code used in the video</summary>

```gleam
import gleam/int
import gleam/list
import lustre
import lustre/attribute
import lustre/element
import lustre/element/html
import lustre/event

type Model =
  List(#(Int, String))

type Msg {
  Update(Int, String)
  Prepend
  Append
}

fn update(model: Model, msg: Msg) -> Model {
  let max = list.fold(model, 0, fn(a, b) { int.max(a, b.0) })

  case msg {
    Prepend -> [#(max + 1, ""), ..model]

    Append -> list.append(model, [#(max + 1, "")])

    Update(id, payload) ->
      list.map(model, fn(x) {
        case x.0 == id {
          True -> #(x.0, payload)
          False -> x
        }
      })
  }
}

fn view(model: Model) -> element.Element(Msg) {
  html.div([], [
    html.ol(
      [],
      list.map(model, fn(x) {
        html.li([], [
          html.textarea([event.on_input(Update(x.0, _))], x.1),
          html.p([], [element.text("Value: "), element.text(x.1)]),
        ])
      }),
    ),
    html.button([event.on_click(Prepend)], [element.text("Prepend")]),
    html.button([event.on_click(Append)], [element.text("Append")]),
  ])
}

pub fn main() {
  let app = lustre.simple(fn(_) { [] }, update, view)

  let _ = lustre.start(app, "#app", Nil)

  Nil
}

```
</details>

Perhaps related to this TODO comment:
https://github.com/lustre-labs/lustre/blob/03bd6f887b45fe183c245dcdef8e44d319cbdf02/src/vdom.ffi.mjs#L181-L182

### `element.keyed()`

Since morphing process causes this bug, you can avoid this bug by using `element.keyed()`.

### `value` property

While `<textarea>` doesn't support `value` attribute, `HTMLTextAreaElement` does support `value` property.
Setting `value` property fixes this update bug as well.

```diff
  fn view(model: Model) -> element.Element(Msg) {
    html.div([], [
      html.ol(
        [],
        list.map(model, fn(x) {
          html.li([], [
            html.textarea(
-              [event.on_input(Update(x.0, _))],
+              [attribute.property("value", x.1), event.on_input(Update(x.0, _))],
              x.1,
            ),
            html.p([], [element.text("Value: "), element.text(x.1)]),
          ])
        }),
      ),
      html.button([event.on_click(Prepend)], [element.text("Prepend")]),
      html.button([event.on_click(Append)], [element.text("Append")]),
    ])
  }
```

**Comment by hayleigh-dot-dev** [comment]
You should always use `keyed` when rendering dynamic content in a list, otherwise you will run into focus/input related problems _anyway_: it's what `keyed` is for!

I'll still investigate because this behaviour looks funky regardless, thanks.

**Comment by hayleigh-dot-dev** [comment]
I think I'm going to close this as a wontfix for the time-being. I think this is a real motivating use for keyed children and using them _does_ solve the problem so I think for now I'll consider this as working acceptably.

If you come up against this again feel-free to re-open with additional info/context!

**Comment by pocka** [comment]
I felt this unintuitive/surprising because the 2nd argument of the `html.textarea` function being `String` instead of `List(Element(msg))`. I know `<textarea>` only accepts TextNode elements, but seeing this signature made me think "oh, this library abstracts `<textarea>` shenanigans away, great!" (like [React does](https://react.dev/reference/react-dom/components/textarea)) If I knew `element/html` do nothing special for attributes/events beforehand, this does not occur though.

However I understand and agree that vdom layer should keep element specific behaviors as minimal as possible. Web Components are widely supported nowadays and browser vendors are still adding native elements... 

Anyway, at least documentation updates to [`element.keyed`](https://hexdocs.pm/lustre/4.3.6/lustre/element.html#keyed) would be preferred IMO. That function is _necessary_ one, not just an optimization one. Also situations this function is required are not limited to list renderings. Related: #146.

**Comment by hayleigh-dot-dev** [comment]
> I felt this unintuitive/surprising because the 2nd argument of the html.textarea function being String instead of List(Element(msg)). I know <textarea> only accepts TextNode elements, but seeing this signature made me think "oh, this library abstracts <textarea> shenanigans away, great!" (like [React does](https://react.dev/reference/react-dom/components/textarea)) If I knew element/html do nothing special for attributes/events beforehand, this does not occur though.

i thought this would be a nice QoL change compared to elm. Input’s don’t take children, as another example. This is an interesting perspective though, thanks. 

You’re right I think this should be fixed.

**Comment by hayleigh-dot-dev** [comment]
Fixed 💪
