### ISSUE TITLE
server_component.set_selector doesn't work

### ISSUE THREAD

**Issue by Nicd** [lustre-labs/lustre#171]
As far as I understand it, a new subject is being created here but then it's thrown away and nothing selects from it, so the `SetSelector` call is not received: https://github.com/lustre-labs/lustre/blob/c12908cbf31f553b5ec628755b6a6c3b0ce72fdc/src/lustre/server_component.gleam#L220

**Comment by hayleigh-dot-dev** [comment]
`set_selector` has now been deprecated in favour of `select` https://hexdocs.pm/lustre/lustre/server_component.html#select. This `Effect` gives you access to both the dispatch function also given to `effect.from` _and_ a fresh subject that you can hand to other actors. You are expected to return a selector from this function, and typically that would be a selector for this fresh subject, but it could be anything. It will be merged with any selectors already set up.
