### ISSUE TITLE
Claim on main page of documentation: "Elm meets Phoenix LiveView"

### ISSUE THREAD

**Issue by human154** [lustre-labs/lustre#177]
At the heart of liveview, as I understand it, is a mechanism to communicate seamlessly between front-end and back-end.
I'm intrigued by this claim on the main page of lustre docs: 

"Universal components. Write once, run anywhere. Elm meets Phoenix LiveView"

I wasn't able to find any documentation on a feature in lustre which approximates liveview.  Did I miss it?

I also heard Louis make a similar parallel to liveview, i think in the gleam 1.0 presentation.

If lustre doesn't have liveview-like functionality, or there is no documentation on this yet, then perhaps the claim should be removed for now, to save people the frustration of searching.  (again sorry if I'm a dummy and missing something obvious).

**Comment by hayleigh-dot-dev** [comment]
You can find the api reference for server components here: https://hexdocs.pm/lustre/lustre/server_component.html

An example of how to set them up using mist here: https://github.com/lustre-labs/lustre/tree/main/examples/99-server-components

And here is a repo showcasing the same lustre application used as a SPA, a web component, and as a server component: https://github.com/hayleigh-dot-dev/lustre-universal-component-demo/tree/main
