### ISSUE TITLE
Lustre 4.4.0 regression `TypeError: element.children is undefined`

### ISSUE THREAD

**Issue by mdarse** [lustre-labs/lustre#179]
Hi, since an accidental update to latest version 4.4.0, the app I’m working on is broken.

Not sure what's happening here, but here is a screenshot while paused on the crash, I think it may be related to fragments because there is no `children` property:

<img width="835" alt="Capture d’écran 2024-09-06 à 06 01 53" src="https://github.com/user-attachments/assets/370433a4-9cb1-428c-a51a-84adabe05a5f">

I’m just had a look at the changes since 4.3.6 and I’m not sure I understand the rationale behind the new generators stuff.

Don’t hesitate if more information is needed to reproduce the issue.

**Comment by hayleigh-dot-dev** [comment]
Ah thank you, good spot! 4.4.1 will be released in a second with the fix, sorry!
