### ISSUE TITLE
Component change handler compares equality of payload to message

### ISSUE THREAD

**Issue by Nicd** [lustre-labs/lustre#18]
Re: https://discord.com/channels/768594524158427167/768594524158427170/1163057856514375761

In https://github.com/lustre-labs/lustre/blob/dbf232acb059f9f3f8972242b68a9384b1290dd4/src/lustre.ffi.mjs#L195 `prev` is being compared to `decoded[0]` but `prev` is `a` and `decoded[0]` is `SomeMessage(a)`, so the equality check will always fail and cause a re-render.

**Comment by hayleigh-dot-dev** [comment]
Thanks! fixed in v3.0.9
