### ISSUE TITLE
Does lustre support WebSocket?

### ISSUE THREAD

**Issue by reedchan7** [lustre-labs/lustre#182]
Hello, I am currently looking for an HTTP framework in the *Gleam* ecosystem that supports **WebSocket**.
I have noticed the *wisp* project and *lustre*, but after reviewing the documentation, it seems that lustre doesn’t directly support WebSocket.

Could you please confirm if lustre now supports WebSocket?
If so, where can I find the documentation and examples?
If not, is there any plan to support it soon?”

**Comment by metruzanca** [comment]
Lustre does not handle any server logic. Lustre lets you bring your own web server/framework which can then use Lustre components to render your application (either server side or clientside). If you want websockets, take a look at [Mist](https://github.com/rawhat/mist). There's a guide in the docs about how to use [Lustre with Mist](https://hexdocs.pm/lustre/guide/05-server-side-rendering.html).

> Not affiliated w/ lustre, just saw the issue, thought I'd drop a helping message.

**Comment by hayleigh-dot-dev** [comment]
Yup that's right, Lustre isn't a backend web framework! For consuming web sockets as a client though, there is this package someone made: https://hexdocs.pm/lustre_websocket/
