### ISSUE TITLE
Placeholder text in "Lustre for React Devs" documentation

### ISSUE THREAD

**Issue by schalkventer** [lustre-labs/lustre#184]
I'm not sure whether it is a bug? However I assume it is simply placeholders that need to be populated with content?

If this is the case, I'm happy to add some initial contemtI initial, since I have quite bit of experience with React and Elm - and have just started playing around with Lustre on some hobby projects.

**Comment by hayleigh-dot-dev** [comment]
Would be great to get some contributions there!

**Comment by metruzanca** [comment]
> Would be great to get some contributions there!

Done! :) https://github.com/lustre-labs/lustre/pull/192

**Comment by schalkventer** [comment]
Thanks @metruzanca !
