### ISSUE TITLE
Custom element (component) is not swapped for another component

### ISSUE THREAD

**Issue by Nicd** [lustre-labs/lustre#19]
Repro case: https://codesandbox.io/p/sandbox/strange-heisenberg-s449ny?file=%2Fsrc%2Fapp.gleam%3A46%2C16

First, comp-b should be rendered (as it is). When the counter is raised above 5, comp-a should be rendered instead, but it never is. If you set a breakpoint in `createElement`, you can see that comp-a is created, but it never appears in the DOM.

**Comment by hayleigh-dot-dev** [comment]
This was a silly bug where I had an important line of code above a curly brace instead of below it 🙃 Fixed in v3.0.9!
