### ISSUE TITLE
Error when attempting to set SVG presentational attributes from server component

### ISSUE THREAD

**Issue by JonasGruenwald** [lustre-labs/lustre#197]
Hello, another server component issue I found, although I'm not 100% sure if I'm doing everything correctly here though, let me know if I'm missing something.

What I am trying to do is render some dynamic SVG elements, by setting their presentational attributes based on the lustre model, however updates of those attributes after the first render fail with an error.

### Steps

* Using the server components example as a basis: https://github.com/lustre-labs/lustre/tree/main/examples/99-server-components
* Replace the view function with this one:
```gleam
fn view(model: Model) -> Element(Msg) {
  let styles = [#("width", "100vw"), #("height", "100vh"), #("padding", "1rem")]
  let count = int.to_string(model)
  ui.centre(
    [attribute.style(styles)],
    ui.stack([], [
      ui.button([event.on_click(Incr)], [element.text("+")]),
      html.slot([]),
      html.p([attribute.style([#("text-align", "center")])], [
        element.text(count),
      ]),
      ui.button([event.on_click(Decr)], [element.text("-")]),
      // --- ADDDED THIS PART vvv
      html.svg(
        [
          attribute.attribute("viewBox", "0 0 10 4"),
          attribute.attribute("height", "50px"),
        ],
        [
          svg.rect([
            attribute.attribute("x", "0"),
            attribute.attribute("y", "0"),
            attribute.attribute("fill", "red"),
            attribute.attribute("width", int.to_string(model)),
            attribute.attribute("height", "4"),
          ]),
          svg.rect([
            attribute.attribute("x", int.to_string(model)),
            attribute.attribute("y", "0"),
            attribute.attribute("fill", "blue"),
            attribute.attribute("width", int.to_string(model)),
            attribute.attribute("height", "4"),
          ]),
        ],
      ),
      // --- UNTIL HERE ------^^^
    ]),
  )
}
```
* Run the app and start increasing the counter 

### What happens

* As the counter increases, the first rectangle (red) is updated accordingly to increase its width
* The second rectangle blue is not updated at all
* In the browser console, the following error appears:
```
Uncaught TypeError: Cannot set property width of #<SVGRectElement> which has only a getter
    at patch (lustre-server-component.mjs:97:20)
    at #diff (lustre-server-component.mjs:566:5)
    at LustreServerComponent.messageReceivedCallback (lustre-server-component.mjs:498:26)
    at WebSocket.<anonymous> (lustre-server-component.mjs:488:31)
```
<img width="1013" alt="Screenshot 2024-10-23 at 18 08 57" src="https://github.com/user-attachments/assets/aaf3ba23-049f-4364-986b-691fed92fb43">

### Notes

* The `width` property on the `rect` element is indeed readonly, but I explicitly used `attribute.attribute` not `attribute.property`, so I didn't expect it to try to set the property
* I suspect the reason the first element in the list succeeds to update is because lustre calls `setAttribute` first, then tries to also set the property and after failing there, does not proceed to the next element. This is confirmed when commenting out the second element, the error logged to the console persists, so it's failing on the first element before ever getting to the second

### Workaround

For my use case, I think I'll be fine setting geometry properties via CSS styles instead, which avoids the attribute setting issue entirely, for reference here is how my given example would be fixed:

```gleam
     // --- ADDDED THIS PART vvv
      html.svg(
        [
          attribute.attribute("viewBox", "0 0 10 4"),
          attribute.attribute("height", "50px"),
        ],
        [
          svg.rect([
            attribute.attribute("x", "0"),
            attribute.attribute("y", "0"),
            attribute.attribute("fill", "red"),
            attribute.style([#("width", int.to_string(model))]),
            attribute.attribute("height", "4"),
          ]),
          svg.rect([
            attribute.style([
              #("x", int.to_string(model)),
              #("width", int.to_string(model)),
            ]),
            attribute.attribute("y", "0"),
            attribute.attribute("fill", "blue"),
            attribute.attribute("height", "4"),
          ]),
        ],
      ),
      // --- UNTIL HERE ------^^^
```
(Although for Firefox to show this correctly, the CSS properties need a unit like "px" appended)

**Comment by hayleigh-dot-dev** [comment]
Ahh thank you for opening these issues, I'll get to them as soon as I have time: I'm in the middle of a move across countries right now! This one looks like a simple fix at least.

**Comment by JonasGruenwald** [comment]
Thank you work your work on the package, I very much enjoy using it!
there is no rush with these, found a workaround for everything so far 😌

**Comment by hayleigh-dot-dev** [comment]
> I suspect the reason the first element in the list succeeds to update is because lustre calls setAttribute first, then tries to also set the property and after failing there

Yep this was right. Now only the `value` and `selected` attributes will set the property too, to match the behaviour of the client vdom.
