### ISSUE TITLE
`<lustre_server_component />` in the face of network issues

### ISSUE THREAD

**Issue by LostKobrakai** [lustre-labs/lustre#208]
There doesn't seem to be any reconnect attempts made by `<lustre_server_component />` in case of the websocket connection being dropped – leaving server components in a broken state. There should likely be some way to react to connection loss as well as attempts to reestablish connection.

**Comment by JonasGruenwald** [comment]
@hayleigh-dot-dev would you accept a PR for a very bare bones reconnect mechanism?

I added one in a copy of the server component script in my project, it works alright (after also fixing #218 there)
https://github.com/JonasGruenwald/spectator/blob/c4dc366e1138b57744817ec408fd0c6cfb499cf0/priv/lustre-server-component.mjs#L558C1-L582C4

**Comment by hayleigh-dot-dev** [comment]
Oh yes absolutely! i’m in the middle of moving my life across countries so any PRs (including one character!) would be very welcome 💕

**Comment by hayleigh-dot-dev** [comment]
Closing this thanks to @JonasGruenwald's latest PR. In the future we can flesh this out but for now a simple reconnect mechanism will be included.
