### ISSUE TITLE
A lot of `deprecated` warnings when following the Quickstart example

### ISSUE THREAD

**Issue by Schweber** [lustre-labs/lustre#222]
I'm totally new to gleam and lustre, so i might be missing something:

I'm using gleam 1.6.2 and lustre 4.6.3 and followed the [Quickstart guide](https://hexdocs.pm/lustre/guide/01-quickstart.html) until and including `gleam run -m lustre/dev start`. The program compiled and ran successfully (i can visit it in my browser under 127.0.0.1:1234) but it threw a lot of `deprecated` warnings (see [Pastebin](https://pastebin.com/BemXb3Vj)).

Does lustre need an update or do i need to do something on my system?

**Comment by hayleigh-dot-dev** [comment]
Hi there! You can see that none of these deprecations come from lustre so there's nothing for me to do about it. Recently the standard library deprecated a lot of modules and functions as we prepare to release v1 and move parts out into separate packages.
