### ISSUE TITLE
Rendering lists page's example code does not match the quickstart program.

### ISSUE THREAD

**Issue by cncptpr** [lustre-labs/lustre#226]
The [rendering lists page](https://github.com/lustre-labs/lustre/blob/main/pages/hints/rendering-lists.md#fixing-the-quickstart-program) uses the cat as a `String` (probably the id), but the [quickstart program](https://github.com/lustre-labs/lustre/blob/main/pages/guide/01-quickstart.md) uses a `Cat(id: String, url: String)` type.

It just confused me after doing the quickstart and then reading that page.

I think the following code is the correct one with the current quickstart:
```gleam
element.keyed(
  html.div([], _),
  list.map(model.cats, fn(cat) {
    #(
      cat.id,
      html.img([
        attribute.src(cat.url),
        attribute.width(400),
        attribute.height(400),
      ]),
    )
  }),
),
```

**Comment by hayleigh-dot-dev** [comment]
Ah good spot, thank you!
