### ISSUE TITLE
Server components with JavaScript backend

### ISSUE THREAD

**Issue by ohurvitz** [lustre-labs/lustre#230]
I'm interested in this because I'm thinking of build an app in the following way:
- Make the app use server components for all data coming from the server (think todo list app - just render on the server, like liveview)
- No add a service worker that captures the websocket and runs the logic on the client, with some database solution (indexeddb as an option), and performs background sync between that database and the server.
This allows me to have online and offline clients, and debug on the server initially.

I'm happy to try and get this to work, but would like some input as to what prevents server components from working with the JavaScript backend right now.

**Comment by hayleigh-dot-dev** [comment]
Hey that's a super interesting use-case, definitely an idea I'd love to pursue for Lustre. Currently there _is_ an implementation of the server component runtime for javascript; you should be able to use `lustre.start_server_component` and it'll work.

The caveat is that this runtime is super untested, I think you would be the first user. Very happy to work out any hiccups or problems you run into though!

**Comment by ohurvitz** [comment]
I'll need to figure out how to create a service worker using gleam. I will start by creating a basic app with server components to get a feel for it, then try to add this layer. I'll reach out for help if needed. 
I'm thinking we can close this issue as the functionality exists (though untested) and I can create issues or contribute fixes as I hit them.
