### ISSUE TITLE
File IO failure while compiling Lustre

### ISSUE THREAD

**Issue by GiregL** [lustre-labs/lustre#231]
Hi !

On Windows 11, I created a new project in gleam with `gleam new ...` and added some dependencies such as Wisp and Lustre. I then copied the routing tutorial part of Wisp and attempted to run it. I got this error:

```
  Compiling lustre
error: File IO failure

An error occurred while trying to link this file:

    C:\Users\_\Desktop\Lab\gleam\test\build\dev\erlang\lustre\priv

The error message from the file IO library was:

    Le client ne dispose pas d’un privilège nécessaire. (os error 1314)


Windows does not support symbolic links without developer mode
or admin privileges. Please enable developer mode and try again.

https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development#activate-developer-mode
```

(The error in french says: `The client does not have a necessary privilege.`)

I know I can resolve this by compiling in administrator mode but maybe it should be nice to have this fixed ? In case the user cannot use administrator mode and needs to work with Lustre for example.

**Comment by hayleigh-dot-dev** [comment]
This isn't a problem with Lustre (or its dev tools) and it's unfortunately not something that we can fix. Gleam creates symlinks to a package's `priv/`: the relevant issue on the Gleam repo is [here](https://github.com/gleam-lang/gleam/issues/3015).

It is unfortunate but also out of my hands :c
