### ISSUE TITLE
Boolean attributes don't seem to apply

### ISSUE THREAD

**Issue by brattonross** [lustre-labs/lustre#55]
Using boolean attributes on elements doesn't appear to work as expected, I'm only using lustre to render html elements to strings, so I'm not sure if this affects the SPA side of things.

For example:

```gleam
import gleam/io
import lustre/attribute
import lustre/element
import lustre/element/html

// executing the following I would expect "<input disabled>", but we get "<input>"
pub fn main() {
  html.input([attribute.disabled(True)])
  |> element.to_string
  |> io.println
}
```

I would assume that this is because boolean attributes are being registered as properties, instead of attributes, and so we are never hitting [the boolean case here](https://github.com/lustre-labs/lustre/blob/1059d622e496d8a301c0ab9278a7ab13ac276a8e/src/lustre/internals/vdom.gleam#L330-L334), but that's just a guess from a quick glance at the code.

Happy to take a look and make a PR

**Comment by hayleigh-dot-dev** [comment]
> I would assume that this is because boolean attributes are being registered as properties, instead of attributes, and so we are never hitting [the boolean case here](https://github.com/lustre-labs/lustre/blob/1059d622e496d8a301c0ab9278a7ab13ac276a8e/src/lustre/internals/vdom.gleam#L330-L334), but that's just a guess from a quick glance at the code.

Hmm no that case should still be hit, I will investigate!

**Comment by hayleigh-dot-dev** [comment]
Fixed and will be live either in the next rc or v4 if i publish that instead :)

**Comment by brattonross** [comment]
Great, thanks!
