### ISSUE TITLE
tabindex attribute not being correctly removed from element.

### ISSUE THREAD

**Issue by CrowdHailer** [lustre-labs/lustre#77]
<img width="693" alt="Screenshot 2024-03-27 at 09 27 43" src="https://github.com/lustre-labs/lustre/assets/5862302/bc562d74-3bd0-444b-b332-b04994157285">

tabindex attribute is persisting on elements where it is no longer set.
In the attached screenshot the blue highlighed line has a "tabindex" value that is not set in the render function.
I am 100% sure that it's not set in the render function because the circled div is created in the same `list.map` call. 

There is a tabindex value set in similarly nested div in a different component. which is the one highlighted below. So I think for some reason it is not being cleared when diffing properly

The code is here https://github.com/CrowdHailer/eyg-lang/blob/4ae1953e77e3b0fdab13c83eaf8ae997a2b59bd2/eyg/src/spotless/view/page.gleam#L21-L38

`page.surface` is the function that is used to render the very last element and sets a tabindex.
`render.top` is the function that renders an element without tabindex set.

**Comment by hayleigh-dot-dev** [comment]
Hmm thanks, looks like an issue with the dom patching.

**Comment by CrowdHailer** [comment]
<img width="686" alt="Screenshot 2024-03-31 at 18 52 40" src="https://github.com/lustre-labs/lustre/assets/5862302/b8f1c744-7233-40d3-90eb-a18c4718e174">

I've upgraded to 4.1.1 Unfortunately these errors are the result. I'll try and look a bit deeper later

**Comment by hayleigh-dot-dev** [comment]
🤨 oh dear that doesn't look good at all. Can you open a separate issue please.
