### ISSUE TITLE
Support for `html.keyed`?

### ISSUE THREAD

**Issue by ghivert** [lustre-labs/lustre#79]
Hi!

Is there any support planned for `html.keyed`, like [`Html.Keyed`](https://package.elm-lang.org/packages/elm/html/latest/Html.Keyed) in elm?

Thanks!

**Comment by hayleigh-dot-dev** [comment]
Eventually, yes. Imminently, probably not unless some brave soul dives into the vdom code and PRs it themselves. With regard to vdom and perf-related things I've taken the approach of solving problems as they come up for real users: and so far apps have been small enough (mostly) for this to not be an issue.

If you have a specific perf issue I'd be happy to discuss it, but otherwise we'll have to leave things at a hand-wavey "yeah eventually" ^.^

**Comment by ghivert** [comment]
OK, I was almost sure about the situation, but I wanted to be sure before diving in the code.

---

I'm developing a toast module (a little bit à la react-toastify) to inject in the frontend directly, and I'm using Lustre to handle the internal state of the module. Actually, everything is great until I started to add animations, because of the stateful nature of HTML.

Let's illustrate what I say:

1. Add a toast, queue in lustre is `[Toast(id: 1, content: bla)]`.
Conceptually, we would like to have: 
```
[stack]
  [toast 1 with animation start to display]
[/stack]
```

In the DOM:
```html
<div>
  <toast-animated id=1 [underlying-id="first-toast"]>bla</toast-animated>
</div>
```

2. Add a toast, queue in lustre is `[Toast(id: 2, content: bla), Toast(id: 1, content: bla)]`
Conceptually, we would like to have: 
```
[stack]
  [toast 2 with animation start to display] 
  [toast 1 with animation continues to display]
[/stack]
```
In the DOM: 
```html
<div>
  <toast-animated id=2 [underlying-id="first-toast"]>bla</toast-animated>
  <toast-animated id=1 [underlying-id="second-toast"]>bla</toast-animated>
</div>
```

Unfortunately, what's happening under the hood is that lustre is correctly updating the DOM, but the first node in the DOM had an animation running. Lustre will just update the content and the attributes, and animation will continue to run, because the `[underlying-id]` maintained by the browser will not change. That's why I need to have keys for nodes: to make sure lustre will not update existing nodes with new data.

Am I clear in my explanations? 😅

**Comment by hayleigh-dot-dev** [comment]
Ahhhh yep that makes total sense – seems pretty important! I'll see what I can do but I can't give a time estimation at the moment.

**Comment by ghivert** [comment]
Thanks a lot for your reactivity and your help! No worry, I can live without animations first, or do things with rAF, but I think it was valuable to bring the subject on the table!
