### ISSUE TITLE
failed to execute remove node

### ISSUE THREAD

**Issue by CrowdHailer** [lustre-labs/lustre#94]
<img width="686" alt="Screenshot 2024-03-31 at 18 52 40" src="https://github.com/lustre-labs/lustre/assets/5862302/d3582d00-1af9-4c78-9c0b-00345d603866">

first reported in #77

**Comment by hayleigh-dot-dev** [comment]
Can you try v4.1.2 please?

**Comment by CrowdHailer** [comment]
Tried with 4.1.4. appears to be fixed
